### ISSUE TITLE
Upper part of image output from test.sh looks incorrect

### ISSUE THREAD

**Issue by hs118** [bcmi/MadisNet-Inharmonious-Region-Localization#2]
When I run test.sh, only the upper part of the output retouched image looks noticeably wrong. I've gone through the code but couldn't pinpoint the cause, so I wanted to inquire about it.
![c1374_171515_1](https://github.com/bcmi/MadisNet-Inharmonious-Region-Localization/assets/73328256/12b6d77d-117a-4963-ab52-f76c8ab351f9)

**Comment by ustcnewly** [comment]
Our released model indeed has this issue, but it does not have much effect on the final predicted mask.

**Comment by hs118** [comment]
Thank you for your quick response to the two issues.
